### ISSUE TITLE
Wagtail Version Upgrade

### ISSUE THREAD

**Issue by rhodges** [MidAtlanticPortal/marco-portal2#10]
According to the docs Wagtail v1.3.1 supports Django v1.7 and above
Currently we run:
* Django v1.7.11
* Wagtail v0.8.5

Upgrading to Wagtail v0.8.6 breaks  and we don't know (exactly) why. 
Debug details below.

**Comment by rhodges** [comment]
```
File "......marco_portal2/local/lib/python2.7/site-packages/compressor/conf.py", line 5, in <module>
    from django.template.utils import InvalidTemplateEngineError
ImportError: No module named utils
```

**Comment by rhodges** [comment]
The issue is django-compressor v2.2:
https://django-compressor.readthedocs.io/en/latest/changelog/#v2-2-2017-08-16 
v2.0 dropped support for django 1.7

Shifting back to django-compressor v1.6 seems to fix it.
Testing...

**Comment by rhodges** [comment]
requirements.txt specifies django-compressor==1.4... who installed v2.2?

**Comment by rhodges** [comment]
django-libsass has a requirement for 'django-compressor>=1.3' - that installation may be the one grabbing the latest version.

**Comment by rhodges** [comment]
New error arises in django-modelcluster:
AttributeError: 'ManyToOneRel' object has no attribute 'get_accessor_name'
Seems version dependent again
* currently installed: v3.1
* listed in requirements: 0.6.2
* recommended for latest wagtail: "django-modelcluster>=1.1,<1.2"

**Comment by rhodges** [comment]
installing 1.1 led to error:
```
File "/home/vagrant/.virtualenvs/marco_portal2/local/lib/python2.7/site-packages/django/core/management/base.py", line 414, in check
    raise CommandError(msg)
django.core.management.base.CommandError: System check identified some issues:

ERRORS:
menu.MenuEntry.menu: (modelcluster.E001) ParentalKey must point to a subclass of ClusterableModel.
	HINT: Change menu.Menu into a ClusterableModel or use a ForeignKey instead.
welcome_snippet.WelcomePageEntry.welcome_page: (modelcluster.E001) ParentalKey must point to a subclass of ClusterableModel.
	HINT: Change welcome_snippet.WelcomePage into a ClusterableModel or use a ForeignKey instead.
```
Installing 0.6.2 seems to run.

**Comment by rhodges** [comment]
Installing wagtail v0.8.7 (from v0.8.6) reinstalled compressor 2.2 and modelcluster 3.1

**Comment by rhodges** [comment]
```
pip install --upgrade wagtail==0.8.8, django-modelcluster==0.6.2, django-compressor==1.6
```
preserved versions during upgrade - needed to restart django dev server

**Comment by rhodges** [comment]
wagtail 0.8.8 works with the existing reqs.
It also uses django-taggit==0.12.3
Wagtail 1.0 installed a new version of django-taggit (0.22.1) vwhich seems to expect UUIDs, something that was added in Django 1.8.

**Comment by rhodges** [comment]
Taggit v0.22 dropped support for django 1.7
```
pip install --upgrade "django-taggit<0.22"
```

Wagtail 1.0 crashes with:
```
ProgrammingError at /admin/
column wagtailcore_page.first_published_at does not exist
LINE 1: ...ore_page"."expired", "wagtailcore_page"."locked", "wagtailco...
```

**Comment by rhodges** [comment]
Wagtail 1.0 works after you run a db migration.
Trying push to 1.3.1:
```
pip install --upgrade wagtail==1.3.1, django-modelcluster==0.6.2, django-compressor==1.6, Django==1.7.1, "django-tagit<0.22"
```

**Comment by rhodges** [comment]
updated 
* djangorestframework from v3.3.2 to v3.7.3
* html5lib from v0.999 to 0.999999999
* Willow from v0.2.1 to 0.2.2
* setuptools from v3.6 to 37.0.0

deleted: wagtail.wagtailsearch.models EditorsPick.
Research showed 0 records in either sandbox or production.

**Comment by rhodges** [comment]
makemigrations added migration 0004 to base:
    - Add field file_size to portalimage
    - Alter field created_at on portalimage
    - Alter field file on portalimage
    - Alter field height on portalimage
    - Alter field tags on portalimage
    - Alter field title on portalimage
    - Alter field uploaded_by_user on portalimage
    - Alter field width on portalimage

**Comment by rhodges** [comment]
preserving djangorestframework is important. 

Nearly final pip update command:
```
pip install --upgrade wagtail==1.3.1, django-modelcluster==0.6.2, django-compressor==1.6, Django==1.7.11, "django-taggit<0.22", djangorestframework==3.3.2
```
Then run a migration

**Comment by rhodges** [comment]
Wagtail 1.3.1 expects to use modelclusters 1.0 or 1.1, and for models referred to by a 'ParentKey' (via modelclusters) to be ClusterModels themselves. Code is fixed.
## Final pip update command:
```
pip install --upgrade wagtail==1.3.1, django-modelcluster==1.1, django-compressor==1.6, Django==1.7.11, "django-taggit<0.22", djangorestframework==3.3.2
```

**Comment by rhodges** [comment]
On sandbox upgrade: Introduced bug:
```
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/home/midatlantic/env/marco_portal2/lib/python2.7/site-packages/django/core/management/__init__.py", line 385, in execute_from_command_line
    utility.execute()
  File "/home/midatlantic/env/marco_portal2/lib/python2.7/site-packages/django/core/management/__init__.py", line 354, in execute
    django.setup()
  File "/home/midatlantic/env/marco_portal2/lib/python2.7/site-packages/django/__init__.py", line 21, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/midatlantic/env/marco_portal2/lib/python2.7/site-packages/django/apps/registry.py", line 108, in populate
    app_config.import_models(all_models)
  File "/home/midatlantic/env/marco_portal2/lib/python2.7/site-packages/django/apps/config.py", line 202, in import_models
    self.models_module = import_module(models_module_name)
  File "/usr/lib64/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/midatlantic/env/marco_portal2/src/madrona-scenarios-master/scenarios/models.py", line 16, in <module>
    from picklefield import PickledObjectField
  File "/home/midatlantic/env/marco_portal2/lib/python2.7/site-packages/picklefield/__init__.py", line 5, in <module>
    from picklefield.fields import PickledObjectField # reexport
  File "/home/midatlantic/env/marco_portal2/lib/python2.7/site-packages/picklefield/fields.py", line 79, in <module>
    class PickledObjectField(_get_subfield_superclass()):
  File "/home/midatlantic/env/marco_portal2/lib/python2.7/site-packages/django/db/models/fields/subclassing.py", line 17, in __new__
    new_class = super(SubfieldBase, cls).__new__(cls, name, bases, attrs)
TypeError: Error when calling the metaclass bases
    metaclass conflict: the metaclass of a derived class must be a (non-strict) subclass of the metaclasses of all its bases
```

--------------------------------
Update command output:
```
(marco_portal2)[midatlantic@web540 mp-visualize-master]$ pip install --upgrade wagtail==1.3.1, django-modelcluster==1.1, django-compressor==1.6, Django==1.7.11, "django-taggit<0.22", djangorestframework==3.3.2
You are using pip version 7.0.3, however version 9.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
Collecting wagtail==1.3.1
  Downloading wagtail-1.3.1-py2.py3-none-any.whl (9.0MB)
    100% |████████████████████████████████| 9.0MB 34kB/s 
Collecting django-modelcluster==1.1
  Downloading django-modelcluster-1.1.tar.gz
Collecting django-compressor==1.6
  Downloading django_compressor-1.6-py2.py3-none-any.whl (126kB)
    100% |████████████████████████████████| 131kB 2.4MB/s 
Requirement already up-to-date: Django==1.7.11 in /home/midatlantic/env/marco_portal2/lib/python2.7/site-packages
Collecting django-taggit<0.22
  Downloading django_taggit-0.21.6-py2.py3-none-any.whl (45kB)
    100% |████████████████████████████████| 49kB 5.2MB/s 
Collecting djangorestframework==3.3.2
  Downloading djangorestframework-3.3.2-py2.py3-none-any.whl (634kB)
    100% |████████████████████████████████| 634kB 673kB/s 
Collecting Unidecode>=0.04.14 (from wagtail==1.3.1)
  Downloading Unidecode-0.04.21-py2.py3-none-any.whl (228kB)
    100% |████████████████████████████████| 229kB 1.5MB/s 
Collecting beautifulsoup4>=4.3.2 (from wagtail==1.3.1)
  Downloading beautifulsoup4-4.6.0-py2-none-any.whl (86kB)
    100% |████████████████████████████████| 90kB 3.6MB/s 
Collecting Pillow>=2.6.1 (from wagtail==1.3.1)
  Downloading Pillow-4.3.0.tar.gz (13.9MB)
    100% |████████████████████████████████| 13.9MB 18kB/s 
Collecting html5lib<1,>=0.999 (from wagtail==1.3.1)
  Downloading html5lib-0.999999999-py2.py3-none-any.whl (112kB)
    100% |████████████████████████████████| 114kB 3.0MB/s 
Collecting django-treebeard==3.0 (from wagtail==1.3.1)
  Downloading django-treebeard-3.0.tar.gz (93kB)
    100% |████████████████████████████████| 94kB 3.6MB/s 
Collecting Willow<0.3,>=0.2.2 (from wagtail==1.3.1)
  Downloading Willow-0.2.2-py2.py3-none-any.whl (106kB)
    100% |████████████████████████████████| 106kB 3.5MB/s 
Collecting pytz>=2015.2 (from django-modelcluster==1.1)
  Downloading pytz-2017.3-py2.py3-none-any.whl (511kB)
    100% |████████████████████████████████| 512kB 903kB/s 
Collecting django-appconf>=0.4 (from django-compressor==1.6)
  Downloading django_appconf-1.0.2-py2.py3-none-any.whl
Collecting olefile (from Pillow>=2.6.1->wagtail==1.3.1)
  Downloading olefile-0.44.zip (74kB)
    100% |████████████████████████████████| 77kB 4.2MB/s 
Collecting setuptools>=18.5 (from html5lib<1,>=0.999->wagtail==1.3.1)
  Downloading setuptools-37.0.0-py2.py3-none-any.whl (481kB)
    100% |████████████████████████████████| 483kB 877kB/s 
Collecting six (from html5lib<1,>=0.999->wagtail==1.3.1)
  Downloading six-1.11.0-py2.py3-none-any.whl
Collecting webencodings (from html5lib<1,>=0.999->wagtail==1.3.1)
  Downloading webencodings-0.5.1-py2.py3-none-any.whl
Building wheels for collected packages: django-modelcluster, Pillow, django-treebeard, olefile
  Running setup.py bdist_wheel for django-modelcluster
  Stored in directory: /home/midatlantic/.cache/pip/wheels/f6/50/ad/9fdbc091b169782136f3a6b2647bc35d0e2ab4655afca23c98
  Running setup.py bdist_wheel for Pillow
  Stored in directory: /home/midatlantic/.cache/pip/wheels/49/97/22/638a2ad41d85bc151da7c987ae644da429a23e95733fabfd76
  Running setup.py bdist_wheel for django-treebeard
  Stored in directory: /home/midatlantic/.cache/pip/wheels/40/35/df/61649266a30fd29e657e750f4794ba88ca443dfc1f073b8f1c
  Running setup.py bdist_wheel for olefile
  Stored in directory: /home/midatlantic/.cache/pip/wheels/20/58/49/cc7bd00345397059149a10b0259ef38b867935ea2ecff99a9b
Successfully built django-modelcluster Pillow django-treebeard olefile
Installing collected packages: djangorestframework, django-taggit, Unidecode, beautifulsoup4, olefile, Pillow, setuptools, six, webencodings, html5lib, django-treebeard, Willow, django-appconf, django-compressor, pytz, django-modelcluster, wagtail
  Found existing installation: djangorestframework 3.1.3
    Uninstalling djangorestframework-3.1.3:
      Successfully uninstalled djangorestframework-3.1.3
  Found existing installation: django-taggit 0.12.2
    Uninstalling django-taggit-0.12.2:
      Successfully uninstalled django-taggit-0.12.2
  Found existing installation: Unidecode 0.4.19
    Uninstalling Unidecode-0.4.19:
      Successfully uninstalled Unidecode-0.4.19
  Found existing installation: beautifulsoup4 4.3.2
    Uninstalling beautifulsoup4-4.3.2:
      Successfully uninstalled beautifulsoup4-4.3.2
  Found existing installation: Pillow 3.2.0
    Uninstalling Pillow-3.2.0:
      Successfully uninstalled Pillow-3.2.0
  Found existing installation: setuptools 17.0
    Uninstalling setuptools-17.0:
      Successfully uninstalled setuptools-17.0
  Found existing installation: six 1.10.0
    Uninstalling six-1.10.0:
      Successfully uninstalled six-1.10.0
  Found existing installation: html5lib 0.999
    Uninstalling html5lib-0.999:
      Successfully uninstalled html5lib-0.999
  Found existing installation: django-treebeard 2.0
    Uninstalling django-treebeard-2.0:
      Successfully uninstalled django-treebeard-2.0
  Found existing installation: django-appconf 1.0.1
    Uninstalling django-appconf-1.0.1:
      Successfully uninstalled django-appconf-1.0.1
  Found existing installation: django-compressor 1.4
    Uninstalling django-compressor-1.4:
      Successfully uninstalled django-compressor-1.4
  Found existing installation: pytz 2016.10
    Uninstalling pytz-2016.10:
      Successfully uninstalled pytz-2016.10
  Found existing installation: django-modelcluster 0.6.2
    Uninstalling django-modelcluster-0.6.2:
      Successfully uninstalled django-modelcluster-0.6.2
  Found existing installation: wagtail 0.8.5
    Uninstalling wagtail-0.8.5:
      Successfully uninstalled wagtail-0.8.5
Successfully installed Pillow-4.3.0 Unidecode-0.4.21 Willow-0.2.2 beautifulsoup4-4.6.0 django-appconf-1.0.2 django-compressor-1.6 django-modelcluster-1.1 django-taggit-0.21.6 django-treebeard-3.0 djangorestframework-3.3.2 html5lib-0.999999999 olefile-0.44 pytz-2017.3 setuptools-37.0.0 six-1.11.0 wagtail-1.3.1 webencodings-0.5.1
```

**Comment by rhodges** [comment]
Note the picklefield module in the error output. I needed to upgrade django-picklefield from 0.3.1 to 0.3.2
```
pip install django-picklefield==0.3.2
```

**Comment by rhodges** [comment]
Also needed to run:
```
python manage.py migrate
python manage.py compress
python manage.py collectstatic -i utfgrid
```
